/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.285
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.model;

import com.finbourne.insights.model.Link;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccessEvaluationLog
 */
public class AccessEvaluationLogTest {
    private final AccessEvaluationLog model = new AccessEvaluationLog();

    /**
     * Model tests for AccessEvaluationLog
     */
    @Test
    public void testAccessEvaluationLog() {
        // TODO: test AccessEvaluationLog
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'userType'
     */
    @Test
    public void userTypeTest() {
        // TODO: test userType
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'authoritativeRoleId'
     */
    @Test
    public void authoritativeRoleIdTest() {
        // TODO: test authoritativeRoleId
    }

    /**
     * Test the property 'authoritativePolicyId'
     */
    @Test
    public void authoritativePolicyIdTest() {
        // TODO: test authoritativePolicyId
    }

    /**
     * Test the property 'authoritativeSelector'
     */
    @Test
    public void authoritativeSelectorTest() {
        // TODO: test authoritativeSelector
    }

    /**
     * Test the property 'resourceType'
     */
    @Test
    public void resourceTypeTest() {
        // TODO: test resourceType
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

    /**
     * Test the property 'resourceFromEffectiveDate'
     */
    @Test
    public void resourceFromEffectiveDateTest() {
        // TODO: test resourceFromEffectiveDate
    }

    /**
     * Test the property 'resourceToEffectiveDate'
     */
    @Test
    public void resourceToEffectiveDateTest() {
        // TODO: test resourceToEffectiveDate
    }

    /**
     * Test the property 'resourceFromAsAt'
     */
    @Test
    public void resourceFromAsAtTest() {
        // TODO: test resourceFromAsAt
    }

    /**
     * Test the property 'resourceToAsAt'
     */
    @Test
    public void resourceToAsAtTest() {
        // TODO: test resourceToAsAt
    }

    /**
     * Test the property 'accessExecutionTime'
     */
    @Test
    public void accessExecutionTimeTest() {
        // TODO: test accessExecutionTime
    }

    /**
     * Test the property 'accessAsAtTime'
     */
    @Test
    public void accessAsAtTimeTest() {
        // TODO: test accessAsAtTime
    }

    /**
     * Test the property 'requiredLicencePolicyId'
     */
    @Test
    public void requiredLicencePolicyIdTest() {
        // TODO: test requiredLicencePolicyId
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
