/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.285
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.model;

import com.finbourne.insights.model.AuditData;
import com.finbourne.insights.model.AuditDataSummary;
import com.finbourne.insights.model.AuditProcess;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuditProcessSummary
 */
public class AuditProcessSummaryTest {
    private final AuditProcessSummary model = new AuditProcessSummary();

    /**
     * Model tests for AuditProcessSummary
     */
    @Test
    public void testAuditProcessSummary() {
        // TODO: test AuditProcessSummary
    }

    /**
     * Test the property 'process'
     */
    @Test
    public void processTest() {
        // TODO: test process
    }

    /**
     * Test the property 'latestEntry'
     */
    @Test
    public void latestEntryTest() {
        // TODO: test latestEntry
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

}
