/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.285
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.model;

import com.finbourne.insights.model.Histogram;
import com.finbourne.insights.model.Link;
import com.finbourne.insights.model.VendorLog;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResourceListWithHistogramOfVendorLog
 */
public class ResourceListWithHistogramOfVendorLogTest {
    private final ResourceListWithHistogramOfVendorLog model = new ResourceListWithHistogramOfVendorLog();

    /**
     * Model tests for ResourceListWithHistogramOfVendorLog
     */
    @Test
    public void testResourceListWithHistogramOfVendorLog() {
        // TODO: test ResourceListWithHistogramOfVendorLog
    }

    /**
     * Test the property 'histogram'
     */
    @Test
    public void histogramTest() {
        // TODO: test histogram
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'nextPage'
     */
    @Test
    public void nextPageTest() {
        // TODO: test nextPage
    }

    /**
     * Test the property 'previousPage'
     */
    @Test
    public void previousPageTest() {
        // TODO: test previousPage
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
