/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.285
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.api;

import com.finbourne.insights.ApiException;
import com.finbourne.insights.model.AccessEvaluationLog;
import com.finbourne.insights.model.LusidProblemDetails;
import com.finbourne.insights.model.LusidValidationProblemDetails;
import com.finbourne.insights.model.ResourceListWithHistogramOfAccessEvaluationLog;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccessEvaluationsApi
 */
@Ignore
public class AccessEvaluationsApiTest {

    private final AccessEvaluationsApi api = new AccessEvaluationsApi();

    
    /**
     * [EXPERIMENTAL] GetAccessEvaluationLog: Get the log for a specific access evaluation.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessEvaluationLogTest() throws ApiException {
        String id = null;
        AccessEvaluationLog response = api.getAccessEvaluationLog(id);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] ListAccessEvaluationLogs: List the logs for access evaluations.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccessEvaluationLogsTest() throws ApiException {
        String filter = null;
        String sortBy = null;
        Integer limit = null;
        String page = null;
        String histogramInterval = null;
        ResourceListWithHistogramOfAccessEvaluationLog response = api.listAccessEvaluationLogs(filter, sortBy, limit, page, histogramInterval);

        // TODO: test validations
    }
    
}
