/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.285
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.api;

import com.finbourne.insights.ApiException;
import com.finbourne.insights.model.AuditEntry;
import com.finbourne.insights.model.CreateAuditEntry;
import com.finbourne.insights.model.LusidProblemDetails;
import com.finbourne.insights.model.LusidValidationProblemDetails;
import com.finbourne.insights.model.ProblemDetails;
import com.finbourne.insights.model.ResourceListOfAuditProcessSummary;
import com.finbourne.insights.model.ScrollableCollectionOfAuditEntry;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuditingApi
 */
@Ignore
public class AuditingApiTest {

    private final AuditingApi api = new AuditingApi();

    
    /**
     * [EARLY ACCESS] CreateEntry: Create (persist) and audit entry..
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEntryTest() throws ApiException {
        CreateAuditEntry createAuditEntry = null;
        AuditEntry response = api.createEntry(createAuditEntry);

        // TODO: test validations
    }
    
    /**
     * [EARLY ACCESS] GetProcesses: Get the latest audit entry for each process.
     *
     * This will never be {null}, though it may be empty.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessesTest() throws ApiException {
        ResourceListOfAuditProcessSummary response = api.getProcesses();

        // TODO: test validations
    }
    
    /**
     * [EARLY ACCESS] ListEntries: Get the audit entries.
     *
     * This will never be {null}, though it may be empty.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEntriesTest() throws ApiException {
        String filter = null;
        String sortBy = null;
        Integer size = null;
        String state = null;
        ScrollableCollectionOfAuditEntry response = api.listEntries(filter, sortBy, size, state);

        // TODO: test validations
    }
    
}
