/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.285
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.api;

import com.finbourne.insights.ApiException;
import com.finbourne.insights.model.LusidProblemDetails;
import com.finbourne.insights.model.LusidValidationProblemDetails;
import com.finbourne.insights.model.Request;
import com.finbourne.insights.model.RequestLog;
import com.finbourne.insights.model.ResourceListWithHistogramOfRequestLog;
import com.finbourne.insights.model.Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RequestsApi
 */
@Ignore
public class RequestsApiTest {

    private final RequestsApi api = new RequestsApi();

    
    /**
     * [BETA] GetRequest: Get the request content for a specific API request.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRequestTest() throws ApiException {
        String id = null;
        Request response = api.getRequest(id);

        // TODO: test validations
    }
    
    /**
     * [BETA] GetRequestLog: Get the log for a specific API request.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRequestLogTest() throws ApiException {
        String id = null;
        RequestLog response = api.getRequestLog(id);

        // TODO: test validations
    }
    
    /**
     * [BETA] GetResponse: Get the response for a specific API request.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResponseTest() throws ApiException {
        String id = null;
        Response response = api.getResponse(id);

        // TODO: test validations
    }
    
    /**
     * [BETA] ListRequestLogs: Get the logs for API requests.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listRequestLogsTest() throws ApiException {
        String filter = null;
        String sortBy = null;
        Integer limit = null;
        String page = null;
        String histogramInterval = null;
        ResourceListWithHistogramOfRequestLog response = api.listRequestLogs(filter, sortBy, limit, page, histogramInterval);

        // TODO: test validations
    }
    
}
