/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.289
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.insights.model.AuditData;
import com.finbourne.insights.model.AuditDataSummary;
import com.finbourne.insights.model.AuditProcess;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AuditProcessSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuditProcessSummary {
  public static final String SERIALIZED_NAME_PROCESS = "process";
  @SerializedName(SERIALIZED_NAME_PROCESS)
  private AuditProcess process;

  public static final String SERIALIZED_NAME_LATEST_ENTRY = "latestEntry";
  @SerializedName(SERIALIZED_NAME_LATEST_ENTRY)
  private AuditData latestEntry;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private AuditDataSummary summary;


  public AuditProcessSummary process(AuditProcess process) {
    this.process = process; 
    return this;
  }

   /**
   * Get process
   * @return process
  **/
  @ApiModelProperty(value = "")
  public AuditProcess getProcess() {
    return process;
  }

  public void setProcess(AuditProcess process) {
    this.process = process;
  }


  public AuditProcessSummary latestEntry(AuditData latestEntry) {
    this.latestEntry = latestEntry; 
    return this;
  }

   /**
   * Get latestEntry
   * @return latestEntry
  **/
  @ApiModelProperty(value = "")
  public AuditData getLatestEntry() {
    return latestEntry;
  }

  public void setLatestEntry(AuditData latestEntry) {
    this.latestEntry = latestEntry;
  }


  public AuditProcessSummary summary(AuditDataSummary summary) {
    this.summary = summary; 
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(value = "")
  public AuditDataSummary getSummary() {
    return summary;
  }

  public void setSummary(AuditDataSummary summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditProcessSummary {\n");
    sb.append("    process: ").append(toIndentedString(process)).append("\n");
    sb.append("    latestEntry: ").append(toIndentedString(latestEntry)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
