/*
 * FINBOURNE Insights API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.358
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.insights.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.insights.model.Link;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * DTO of Finbourne.AspNetCore.Http.TrackingEntry.RequestInformation.
 */
@ApiModel(description = "DTO of Finbourne.AspNetCore.Http.TrackingEntry.RequestInformation.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Request {
  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, List<String>> headers = null;

  public static final String SERIALIZED_NAME_CONTENT_LENGTH = "contentLength";
  @SerializedName(SERIALIZED_NAME_CONTENT_LENGTH)
  private Long contentLength;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "contentType";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private String contentType;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_BODY_WAS_TRUNCATED = "bodyWasTruncated";
  @SerializedName(SERIALIZED_NAME_BODY_WAS_TRUNCATED)
  private Boolean bodyWasTruncated;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  private String method;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links = null;


  public Request headers(Map<String, List<String>> headers) {
    this.headers = headers; 
    return this;
  }

  public Request putHeadersItem(String key, List<String> headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * The headers
   * @return headers
  **/
  @ApiModelProperty(value = "The headers")
  public Map<String, List<String>> getHeaders() {
    return headers;
  }

  public void setHeaders(Map<String, List<String>> headers) {
    this.headers = headers;
  }


  public Request contentLength(Long contentLength) {
    this.contentLength = contentLength; 
    return this;
  }

   /**
   * The actual length of the body, which may be larger than the data recorded in Finbourne.Insights.WebApi.Dtos.Request.Body  (e.g. if actual Body is large, or not convertible to a string)
   * @return contentLength
  **/
  @ApiModelProperty(value = "The actual length of the body, which may be larger than the data recorded in Finbourne.Insights.WebApi.Dtos.Request.Body  (e.g. if actual Body is large, or not convertible to a string)")
  public Long getContentLength() {
    return contentLength;
  }

  public void setContentLength(Long contentLength) {
    this.contentLength = contentLength;
  }


  public Request contentType(String contentType) {
    this.contentType = contentType; 
    return this;
  }

   /**
   * The content type
   * @return contentType
  **/
  @ApiModelProperty(value = "The content type")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public Request body(String body) {
    this.body = body; 
    return this;
  }

   /**
   * The recorded content.
   * @return body
  **/
  @ApiModelProperty(value = "The recorded content.")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }


  public Request bodyWasTruncated(Boolean bodyWasTruncated) {
    this.bodyWasTruncated = bodyWasTruncated; 
    return this;
  }

   /**
   * Determines if the recorded body was truncated.
   * @return bodyWasTruncated
  **/
  @ApiModelProperty(value = "Determines if the recorded body was truncated.")
  public Boolean getBodyWasTruncated() {
    return bodyWasTruncated;
  }

  public void setBodyWasTruncated(Boolean bodyWasTruncated) {
    this.bodyWasTruncated = bodyWasTruncated;
  }


  public Request method(String method) {
    this.method = method; 
    return this;
  }

   /**
   * Method called by the request
   * @return method
  **/
  @ApiModelProperty(value = "Method called by the request")
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }


  public Request url(String url) {
    this.url = url; 
    return this;
  }

   /**
   * URL of the request
   * @return url
  **/
  @ApiModelProperty(value = "URL of the request")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  public Request links(List<Link> links) {
    this.links = links; 
    return this;
  }

  public Request addLinksItem(Link linksItem) {
   
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Request {\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    contentLength: ").append(toIndentedString(contentLength)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    bodyWasTruncated: ").append(toIndentedString(bodyWasTruncated)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
